apiVersion: 1
groups:
    - orgId: 1
      name: AI
      folder: Alerts
      interval: 1m
      rules:
        - uid: deqxru8a7ft34e
          title: Max Tokens Consumption
          condition: C
          data:
            - refId: A
              queryType: table
              relativeTimeRange:
                from: 3600
                to: 0
              datasourceUid: P7E099F39B84EA795
              model:
                editorType: sql
                format: 1
                intervalMs: 1000
                maxDataPoints: 43200
                meta:
                    builderOptions:
                        columns: []
                        database: ""
                        limit: 1000
                        mode: list
                        queryType: table
                        table: ""
                pluginVersion: 4.10.1
                queryType: table
                rawSql: "SELECT max(toInt64OrZero(SpanAttributes['gen_ai.usage.total_tokens']))\r\nFROM otel_traces\r\nWHERE $__timeFilter(Timestamp)\r\nAND SpanAttributes['gen_ai.usage.total_tokens'] != ''"
                refId: A
            - refId: B
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 1000
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          isPaused: false
          notification_settings:
            receiver: grafana-default-email
